### ISSUE TITLE
Zero length rail 

### ISSUE THREAD

**Issue by hsnopi** [ian76g/RailroadOnlineMapper#5]
Warning: Division by zero in /var/www/web960/html/minizwerg/classes/Mapper.php on line 373

Warning: Division by zero in /var/www/web960/html/minizwerg/classes/Mapper.php on line 378

Warning: Cannot modify header information - headers already sent by (output started at /var/www/web960/html/minizwerg/classes/Mapper.php:373) in /var/www/web960/html/minizwerg/upload.php on line 54

**Comment by hsnopi** [comment]
Pull request created https://github.com/ian76g/RailroadOnlineMapper/pull/7

**Comment by ian76g** [comment]
accepted PR
